name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.21.3'
      - run: npm install
      - run: npm run compile
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
      - run: echo "name=$(ls | grep vsix | sort | tail -n 1)" >> $GITHUB_OUTPUT
        id: identify-package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.identify-package.outputs.name}}
permissions:
  contents: write